# 자바의 예외는 크게 두 가지 종류가 있습니다.

![image](https://github.com/user-attachments/assets/9ab12434-dabc-48a3-8238-f0496f8aa821)


## 예외 클래스의 부모 클래스는 Throwable과 Object가 존재한다.

- Throwable() 클래스에서 선언되어 Overriding 되어 자주 사용하는 메서드는 여러가지가 있지만 그 중 자주 사용하는 것은
- getMessage()
- toString()
- printStackTrace()

이렇게 3가지가 있다.
 1. getMessage() : 예외 메시지를 String 형태로 제공받습니다. 어떠한 예외가 발생하였는지 확인할때 매우 유용합니다.
 2. toString() : 예외 메시지를 String 형태로 제공받늣빈다. 그런데 getMessage() 보다 더 자세하게 예외 클래스 이름도 같이 보여준다.
 3. printStackTrace() : 가장 첫줄에는 예외 메시지를 출력하고, 두 번째 줄부터는 예외가 발생하게 된 메소드들의 호출 관계를 출력해준다.


```
    public static void main(String[] args) {
        FinallySample sample = new FinallySample();
        sample.finallySample();
    }

    private void finallySample() {

        int[] intArr = null;
        try{
            intArr = new int[5];
            System.out.println("try 블럭 수행");
            System.out.println(intArr[8]);
        }catch (Exception e){
            System.out.println("catch 블럭 수행");
            System.out.println(intArr.length);
            System.out.println(e.getMessage());
            System.out.println(e.toString());
            e.printStackTrace();
        }finally {
            System.out.println("반드시 실행되어지는 finally 블록입니다.");
        }
        System.out.println("블록 이후의 문장이 수행되어집니다.");

    }
}
// 결과
try 블럭 수행
catch 블럭 수행
5
Index 8 out of bounds for length 5 // getMessage()
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 5 // toString()
반드시 실행되어지는 finally 블록입니다.
블록 이후의 문장이 수행되어집니다.
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 5 // printStackTrace()
	at exception.FinallySample.finallySample(FinallySample.java:16)
	at exception.FinallySample.main(FinallySample.java:7)

```

## 체크예외
- 어플리케이션 로직에서 사용할 수있는 실질적인 최상위 예외 입니다.
- Exception과 그 하위 예외 (런타임예외 제외)는 모두 컴파일러가 체크하는 체크 예외입니다.
- 체크 예외는 잡아서 처리하거나 또는 밖으로 던지도록 선언해야 합니다.
  

## 언체크 예외, 런타임 예외
- 컴파일러가 체크하지 않는 언체크 예외입니다.
- RuntimeException과 그 자식 예외는 모두 언체크 예외입니다.



## Throw
- 자바에서는 throw 키워드를 사용해서 예외를 강제로 발생시킬 수 있습니다.
- new 생성자로 예외 클래스를 초기화하여 던져는데, 이 클래스 생성자에 입력값을 주게되면, catch문의 getMessage() 메서드에서 출력할 메세지를 지정하게 됩니다.
- try 블럭 내에서 throw를 명시하면 예외발생시 try-catch 문과 동일하게 throw 이후의 코드는 수행하지 않고 catch 블럭으로 이동합니다.

```
public class ThrowSample {

    public static void main(String[] args) {
        ThrowSample sample = new ThrowSample();
        sample.throwException(13);

    }

    public void throwException(int number) {
        try {
            if(number > 12){
                throw new Exception("Number is over than 12");
            }
            System.out.println("Number is " + number);
        }catch(Exception e){
            e.printStackTrace();
        }

    }

}
//
java.lang.Exception: Number is over than 12
	at throwEx.ThrowSample.throwException(ThrowSample.java:14)
	at throwEx.ThrowSample.main(ThrowSample.java:7)

```

 - 만약 해당하는 예외가 없다면 발생된 예외는 메서드 밖으로 던져집니다. 즉 호출한 메서드로 예외를 넘긴다는 뜻입니다.
 - 예외가 발생할 수 있는 코드를 작성할 때 try - catch 블록으로 처리하는 것이 기본이지만, 경우에 따라서는 다른 곳에서 예외를 처리하도록 호출한 곳으로 예외를 떠넘길 수도 있습니다

![image](https://github.com/user-attachments/assets/39d10025-0744-4345-95bc-5548780f49ef)
![image](https://github.com/user-attachments/assets/3cf9dbfc-7ef8-4a58-944f-136e3dc2d89e)
 
 - 이럴때 사용하는 방법이 throws입니다.
 - throws는 메소드 선언부 끝에 작성되어 메소드에서 예외를 직접 처리(catch)하지 않은 예외를 호출한 곳으로 떠넘기는 역할을 합니다.
 - throws로 예외를 던지면 이 메서드를 호출한 메서드에서는 반드시 try-catch문으로 예외처리를 진행하던가, 처리하지 못한다면 다른 곳으로 throws 해야합니다.
 - throws 구문에는 여러개의 예외를 나열할 수있습니다.
```
public class ThrowSample {

    public static void main(String[] args) {
    
        ThrowSample sample = new ThrowSample();
        sample.throwException(13);

    }  ==> 예외 처리를 하지 않아서 오류발생.

    public void throwException(int number) throws Exception { // 예외를 호출한 메서드로 던짐
        if(number > 12){
            throw new Exception("Number is over than 12");
        }
        System.out.println("Number is " + number);
    }


}

========================================
1.  public static void main(String[] args) {
        ThrowSample sample = new ThrowSample();
        try {
            sample.throwException(13);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }

2.  public static void main(String[] args) throws Exception{
        ThrowSample sample = new ThrowSample();
        sample.throwException(13);
    
    }
3. public static void main(String[] args) throws NullPointException,Exception{
        ThrowSample sample = new ThrowSample();
        sample.throwException(13);
    
    }


```
 - throws로 던진 예외를 다시 한번 던지는 것은 좋은 습관이 아닙니다. 
 - 가장 좋은 방법은  throws 하는 메서드를 호출하는 메서드에서 try catch문으로 처리하는 것입니다.

## 새로운 예외를 만들 수있다.
- 사용자 커스텀 예외 클래스를 만들려면 부모 클래스인 Exception 클래스를 상속하면 됩니다.

```

public class MyException extends Exception{

    public MyException(){
        super();
    }

    public MyException(String message){
        super(message);
    }


}

====================================================

public class CustomException {
    public static void main(String[] args) {
        CustomException sample = new CustomException();
        try{
            sample.throwMyException(13);
        }catch (MyException e){
            e.printStackTrace();
        }

    }


    public void throwMyException(int number) throws MyException {

        if(number > 12 ){
            throw new MyException("Number is over than 12");
        }

    }
}


```

### 체크 예외 좀 더 보기

![image](https://github.com/user-attachments/assets/26a0223b-2b1c-4b91-a407-754f2b6c179a)

```
public class MyCheckedException extends Exception {
    /**
     * * Exception을 상속받은 예외는 체크 예외가 된다.
     */
    public MyCheckedException(String message){
        super(message);
    }


}
```

- 예외가 제공하는 기본 기능이 있는데, 그 중에 오류 메시지를 보관하는 기능도 있습니다.
- super(message) 로 전달한 메시지는 Throwable에 있는 detailMessage에 보관됩니다.
- getMessage()를 통해서 조회가 가능함.
```
public class Client {
    public void call() throws MyCheckedException{
        throw new MyCheckedException("ex"); // 예외 발생 시키기
    }
}
```


```
public class Service {

    Client client = new Client();
    /*
     * 예외를 잡아서 처리하는 코드
     *
     * */
    public void callCatch() {
        try {
            client.call();
        } catch (MyCheckedException e) { //예외 처리 로직
             System.out.println("예외 처리, message=" + e.getMessage());
        }
        System.out.println("정상 흐름 ,");
    }

    /*
     * 체크 예외를 밖으로 던지는 코드
     *  체크 예외는 예외를 잡지 않고 밖으로 던지려면 throws 예외를 메서드에 필수로 선언해야한다.
     */
    public void callThrow() throws MyCheckedException {
        client.call();
    }

}
```


```
public class CheckedCatchMain {

    public static void main(String[] args) {
        Service service = new Service();
        service.callCatch();
        System.out.println("정상종료");


	service.callThrow();
        System.out.println("정상종료");
    }
}

// 결과 - callCatch
예외 처리, message=ex
정상 흐름 ,
정상종료

public class CheckedCatchMain {

    public static void main(String[] args) throws MyCheckedException {
        Service service = new Service();
        service.callThrow();
        System.out.println("정상종료");
    }
}

// 결과 -callThrow
Exception in thread "main" checked.MyCheckedException: ex
	at checked.Client.call(Client.java:5)
	at checked.Service.callThrow(Service.java:24)
	at checked.CheckedCatchMain.main(CheckedCatchMain.java:10)
```

### callCatch의 진행 과정
![image](https://github.com/user-attachments/assets/607fe73e-c164-4cb6-9462-78105273f81c)


### callThrow의 진행 과정
![image](https://github.com/user-attachments/assets/6120bef9-349a-4dbf-8a7e-25151fbe39a6)


- 체크 예외는 잡아서 직접 처리하거나 또는 밖으로 던지거나 둘중 하나를 개발자가 직접 명시적으로 처리해야한다. 그렇지 않으면 컴파일 오류가 발생한다.
- 컴파일 시점은 자바 코드가 작성된 후, 이를 컴파일러가 바이트코드로 변환하는 과정입니다.
- 컴파일러는 문법적인 오류와 체크 예외(Checked Exception) 처리 여부 등을 검사합니다.
- 컴파일이 성공하면 바이트코드가 생성되며, 이 바이트코드는 이후 런타임 시점에서 JVM에 의해 실행됩니다.


## 언체크 예외 더 알아보기

```

public class MyUncheckedException extends RuntimeException{
    /**
     *  * RuntimeException을 상속받은 예외는 언체크 예외가 된다.
     */
    public MyUncheckedException(String message) {
        super(message);
    }


```

```
public class Client {
    public void call() { // throws를 생략 가능하다.
        throw new MyUncheckedException("ex");
    }
}

```


```
/**
 * * UnChecked 예외는 * 예외를 잡거나, 던지지 않아도 된다.
 * 예외를 잡지 않으면 자동으로 밖으로 던진다.
 */
public class Service {

    Client client = new Client();

    /**
     * 필요한 경우 예외를 잡아서 처리하면 된다.
     */
    public void callCatch() {
        try {
            client.call();
        } catch (MyUncheckedException e) { //예외 처리 로직
            System.out.println("예외 처리, message=" + e.getMessage());
        }
        System.out.println("정상 로직");
    }

    /*
     * 예외를 잡지 않아도 된다. 자연스럽게 상위로 넘어간다. \
     * 체크 예외와 다르게 throws 예외 선언을 하지 않아도 된다.
     */
    public void callThrow() {
        client.call();
    }
}

```

```
public class UncheckedThrowMain {

    public static void main(String[] args) {
        Service service = new Service();
        service.callThrow();
        System.out.println("정상 종료");
    }
}

========================================

public class UncheckedThrowMain {

    public static void main(String[] args) {
        Service service = new Service();
        service.callCatch();
        System.out.println("정상 종료");
    }
}

```

- RunTimeException과 그 하위 예외는 언체크 예외로 분류되어집니다.
- 언체크 예외는 말 그대로 컴파일러가 예외를 체크하지 않는다는 뜻입니다.
- 기본적으로 체크 예외와 동일하나 throws를 생략가능합니다.
- 주로 throws를 생략하지만 중요한 예외의 경우 선언해 두면 가독성이 좋아집니다.
  
  


 
  
